### ISSUE TITLE
niconico Darkmode 動作時に文字が読めなくなる

### ISSUE THREAD

**Issue by AyumuNekozuki** [foooomio/nicorepo-filter#18]
「niconico Darkmode」動作時に、文字が読めなくなります。
![image](https://user-images.githubusercontent.com/47974873/99778987-c27c3080-2b57-11eb-8218-6acba2b28743.png)

## 原因
- niconico Darkmode側で文字色を白(正確には`#F5F5F5`)に指定している
- ニコレポ・フィルターのハイライト設定で明るい系の背景色を指定している
- ニコレポ・フィルター側でデフォルト背景色に `#ffffff` を指定している

以上の影響で文字が読めなくなっています。
今回、フィルター機能による影響は特にないです。

### 案１）ニコレポ・フィルター側で`NicorepoItem-item` にclass付与を行ってもらい、nicodark側で調整を行う
ニコレポフィルター側の現在の仕様として、要素に直接`style`を指定して実装していますが、
それをclass付与+cssで行ってもらい、nicodark側で別途色調整を行う方法です。

#### 内容
各`NicorepoItem-item` にclassを付与してもらい、それをnicodark側で読み取り別途対応します。
- ハイライト設定ごとに別のclass名だととても助かります。
- デフォルト背景色として指定している`#ffffff`は指定しないで頂けると助かります。
- nicodark側で、指定されているクラスを読み取り、少し暗くしたハイライト色を適応させます。

#### 内容
bodyタグにclassを付与してもらい、それをnicodark側で読み取り別途対応します。
- nicodark側で文字色をデフォルト(黒文字)に戻します
- この方法だとハイライト色が明るいのに対し、周りの背景が暗いのでモニタや環境次第では目がチカチカします

### 案３）nicodark側の設定を読み取り、ニコレポ・フィルター側で調整を行う
案１の逆パターンです。
現在、niconico Darkmode実行中は`body`タグに`.niconico-darkmode-setting-true`が付与される仕様です。
それをニコレポ・フィルター側で読み取ってもらい、別途色調整等の対応を行ってもらう方法です。

#### 内容
- `body`タグの`.niconico-darkmode-setting-true`を読み取り、設定ごとに、少し暗くしたハイライト色を適応させる
- デフォルト背景色として指定している`#ffffff`は指定しないで頂けると助かります。

---
どの案でも、`.niconico-darkmode-setting-true`は実行中のみ付与（ユーザー側の操作で瞬時にclassが消えライトモードになる仕様）されるため、直接指定ではなく、class付与+CSSなどで色指定を行っていただいたほうが（個人的には）ありがたいです。

いろいろと仕様変更をお願いすることになりそうですが、ご検討よろしくおねがい致します。

## 参考程度に↓
https://github.com/AyumuNekozuki/niconico-darkmode/issues/30

**Comment by foooomio** [comment]
情報を共有いただきありがとうございます。

> ニコレポ・フィルター側でデフォルト背景色に `#ffffff` を指定している

こちら、了解です。デフォルト色に `#ffffff` を指定しないようにします。

> ニコレポ・フィルターのハイライト設定で明るい系の背景色を指定している

こちらについて、案3で進めたいと考えています。

案1は、背景色を指定する class を付与することができないため、採用が難しいです。事情としては、ハイライト設定を保存する際、背景色を指定する値として、`red` や `green` のような色名ではなく、カラーコードを直接保存しているためです。仮に色名で保存されていれば、`.nicorepo-filter-red` のような class を付与することも可能ですが、それができないため `style` に直接カラーコードを指定しています（余談ですが、カラーコードを直接保存しているのは、ユーザーが自由に色を指定できるようにする拡張を考慮に入れているためです）。

それから案2ですが、やはりダークモードの利点を損なってしまうため、できれば避けたいと思います。

案3の具体的な対応方法ですが、当初は、フィルターの設定にダークモード用のカラーパレットを用意して、ユーザーに色を変えてもらうことを考えていました。しかし、ダークモード切り替え機能がついているので、時間帯によってダークモードを切り替えるような使い方も考えられるのですよね。 ダークモードを切り替えるたびにユーザーに色を変えてもらうのは現実的ではないので、ダークモードの設定を読み取って、自動で色を調整するのが良さそうかなと考えています（実現可能かどうかは調査中です）。

---

それから、私が気づいた点ですが、niconico Darkmode ではニコレポをマウスホバーしたときに、背景色を明るくするようになっていますが、こちらもコンフリクトしてしまっているようです。

**Comment by AyumuNekozuki** [comment]
ご返信ありがとうございます。

>こちら、了解です。デフォルト色に #ffffff を指定しないようにします。

ありがとうございます。よろしくお願い致します。

>こちらについて、案3で進めたいと考えています。

了解です。
パッといい実装方法が思いつかなくて申し訳ないですが、ご検討よろしくお願い致します。

>それから、私が気づいた点ですが、niconico Darkmode ではニコレポをマウスホバーしたときに、背景色を明るくするようになっていますが、こちらもコンフリクトしてしまっているようです。

盲点でした...w
コチラについて、nicodark側で「アクセス済みリンク(visited)のアイテムをホバーしたときに文字が見づらい」という問題が発生していました。そのため、nicodark側で、背景色変更以外の方法（文字色の変更など）に変更する予定です。
ニコレポ・フィルター側ではこれといった対応はしなくてよいかと思います。

**Comment by foooomio** [comment]
75bb53cb3c1180622ddff0117264501c62dda2a4 で対応。v1.6.0 としてリリース。

ハイライト色によっては、ニコレポ右上の日時が見えづらくなるものの、これより暗くすると見栄えが悪くなるため妥協しました。

**Comment by foooomio** [comment]
@AyumuNekozuki ニコレポ右上の日時の配色を変更する予定はないですよね・・・？

こちらの CSS で対応するのも手か・・・？

**Comment by AyumuNekozuki** [comment]
右上日時の配色、こちらの指定漏れでデフォルトのままになってました...！

「◯時間前」の赤文字は変更予定なしです。
日時が表示される灰色文字は、もう少し明るく（ `#666666` → `#c4c4c4` ）にしようと思っています！

**Comment by foooomio** [comment]
> 日時が表示される灰色文字は、もう少し明るく（ #666666 → #c4c4c4 ）にしようと思っています！

ほんとですか！そうしてもらえるとすごくありがたいです！
